name: Download and delete a Build Artifact'
description: 'Download and delete a build artifact that was previously uploaded in the workflow by the upload-artifact action'
inputs:  
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'Destination path'
    required: false
runs:
  using: "composite"
  steps:
    - name: ☁ ⤵ Download artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}

    - name: 🧹 Delete artifact
      uses: geekyeggo/delete-artifact@v1
      with:
        name: ${{ inputs.name }}
